server-port=25572
online-mode=false
allow-flight=true
spawn-protection=0
enable-command-block=true
enable-rcon=true
rcon.port=25582
rcon.password=cursed-live-local
motd=Cursed Walking MOD Live
level-name=world
max-players=8
view-distance=8
simulation-distance=6
